name: sanchaek
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^3.1.1
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

  retrofit: ^1.3.4+1

  fluttertoast: ^7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.9
  json_serializable: ^3.5.1
  mobx_codegen: ^1.1.2
  retrofit_generator: ^1.4.1+3

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
